-- ============================================================================
-- Phase 4b — 02g orphan products
-- Owns: Imperfection #11 (orphan products)
-- Generated by supabase/seed/generator. Do not edit by hand.
-- ============================================================================
-- 50 orphan products: 20 discontinued, 20 never-launched, 10 test data.
-- None of these are referenced by store_inventory, inventory_movements,
-- order_items, or price_list_items.

SET search_path TO raw, public;

-- products: 50 rows
INSERT INTO raw.products (sku, product_name, category_id, brand_id, weight_grams, is_perishable, country_of_origin, base_price, mrp, is_active, launched_at, discontinued_at) VALUES
  ('BB-00011', 'Britannia Marie Gold 200g (DISC)', 1, 10, NULL, NULL, NULL, 153.52, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00012', 'Lays Magic Masala 50g (DISC)', 1, 10, NULL, NULL, NULL, 143.20, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00013', 'Coca-Cola 600ml Bottle (DISC)', 1, 10, NULL, NULL, NULL, 164.28, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00014', 'Maggi Atta Noodles 80g (DISC)', 1, 10, NULL, NULL, NULL, 167.26, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00015', 'Dabur Honey 250g (DISC)', 1, 10, NULL, NULL, NULL, 50.19, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00016', 'Vim Dishwash Bar 300g (DISC)', 1, 10, NULL, NULL, NULL, 84.87, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00017', 'Surf Excel Easy Wash 1kg (DISC)', 1, 10, NULL, NULL, NULL, 124.59, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00018', 'Closeup Toothpaste 80g (DISC)', 1, 10, NULL, NULL, NULL, 74.73, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00019', 'Vaseline Body Lotion 200ml (DISC)', 1, 10, NULL, NULL, NULL, 212.85, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00020', 'Pears Soap 75g (DISC)', 1, 10, NULL, NULL, NULL, 205.32, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00021', 'Britannia Bourbon 60g (DISC)', 1, 10, NULL, NULL, NULL, 130.00, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00022', 'Haldiram Aloo Bhujia 200g (DISC)', 1, 10, NULL, NULL, NULL, 128.74, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00023', 'Tata Salt 1kg Pouch (DISC)', 1, 10, NULL, NULL, NULL, 200.91, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00024', 'Real Fruit Juice 200ml (DISC)', 1, 10, NULL, NULL, NULL, 56.33, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00025', 'Bournvita 500g (DISC)', 1, 10, NULL, NULL, NULL, 118.87, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00026', 'Horlicks Classic 500g (DISC)', 1, 10, NULL, NULL, NULL, 281.53, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00027', 'Dabur Chyawanprash 250g (DISC)', 1, 10, NULL, NULL, NULL, 162.14, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00028', 'Patanjali Atta 5kg (DISC)', 1, 10, NULL, NULL, NULL, 125.91, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00029', 'Mother Dairy Ghee 500ml (DISC)', 1, 10, NULL, NULL, NULL, 136.61, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00030', 'Amul Cheese Slices 200g (DISC)', 1, 10, NULL, NULL, NULL, 239.28, NULL, FALSE, '2022-06-01', '2024-09-30'),
  ('BB-00031', 'BoltBasket Premium Honey 500g', 1, 10, NULL, NULL, NULL, 295.15, NULL, FALSE, NULL, NULL),
  ('BB-00032', 'BoltBasket Cold-Press Mustard Oil 1L', 1, 10, NULL, NULL, NULL, 102.44, NULL, FALSE, NULL, NULL),
  ('BB-00033', 'Boltkidz Multivitamin Gummies', 1, 10, NULL, NULL, NULL, 181.98, NULL, FALSE, NULL, NULL),
  ('BB-00034', 'BB Organics Quinoa 500g', 1, 10, NULL, NULL, NULL, 289.81, NULL, FALSE, NULL, NULL),
  ('BB-00035', 'BB Premium Cashews 250g', 1, 10, NULL, NULL, NULL, 554.10, NULL, FALSE, NULL, NULL),
  ('BB-00036', 'BB Dailies Hand Cream 100ml', 1, 10, NULL, NULL, NULL, 722.16, NULL, FALSE, NULL, NULL),
  ('BB-00037', 'BB Kitchen Easy-Pour Bottle Cap', 1, 10, NULL, NULL, NULL, 129.97, NULL, FALSE, NULL, NULL),
  ('BB-00038', 'BB Frozen Paneer Tikka 200g', 1, 10, NULL, NULL, NULL, 155.66, NULL, FALSE, NULL, NULL),
  ('BB-00039', 'BB Daily Oat Milk 1L', 1, 10, NULL, NULL, NULL, 733.80, NULL, FALSE, NULL, NULL),
  ('BB-00040', 'BB Daily Almond Milk 1L', 1, 10, NULL, NULL, NULL, 462.46, NULL, FALSE, NULL, NULL),
  ('BB-00041', 'BB Premium Pistachios 200g', 1, 10, NULL, NULL, NULL, 699.64, NULL, FALSE, NULL, NULL),
  ('BB-00042', 'BB Pet Care Cat Food 1kg', 1, 10, NULL, NULL, NULL, 646.31, NULL, FALSE, NULL, NULL),
  ('BB-00043', 'BB Pet Care Dog Treats 250g', 1, 10, NULL, NULL, NULL, 497.90, NULL, FALSE, NULL, NULL),
  ('BB-00044', 'BB Dailies Antiseptic Wipes', 1, 10, NULL, NULL, NULL, 413.69, NULL, FALSE, NULL, NULL),
  ('BB-00045', 'BB Kitchen Stainless Tongs', 1, 10, NULL, NULL, NULL, 536.96, NULL, FALSE, NULL, NULL),
  ('BB-00046', 'BB Daily Sesame Oil 500ml', 1, 10, NULL, NULL, NULL, 482.56, NULL, FALSE, NULL, NULL),
  ('BB-00047', 'BB Daily Coconut Water 1L', 1, 10, NULL, NULL, NULL, 499.87, NULL, FALSE, NULL, NULL),
  ('BB-00048', 'BB Premium Saffron 1g', 1, 10, NULL, NULL, NULL, 685.97, NULL, FALSE, NULL, NULL),
  ('BB-00049', 'BB Daily Brown Rice 1kg', 1, 10, NULL, NULL, NULL, 258.04, NULL, FALSE, NULL, NULL),
  ('BB-00050', 'BB Premium Truffle Oil 100ml', 1, 10, NULL, NULL, NULL, 127.70, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-001', 'TEST PRODUCT — DO NOT USE (1)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-002', 'TEST PRODUCT — DO NOT USE (2)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-003', 'TEST PRODUCT — DO NOT USE (3)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-004', 'TEST PRODUCT — DO NOT USE (4)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-005', 'TEST PRODUCT — DO NOT USE (5)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-006', 'TEST PRODUCT — DO NOT USE (6)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-007', 'TEST PRODUCT — DO NOT USE (7)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-008', 'TEST PRODUCT — DO NOT USE (8)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-009', 'TEST PRODUCT — DO NOT USE (9)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL),
  ('TEST-LOREM-010', 'TEST PRODUCT — DO NOT USE (10)', 1, 10, NULL, NULL, NULL, 1.00, NULL, FALSE, NULL, NULL);

