"""Single source of truth for Phase 4b seed generator constants."""
import hashlib
from datetime import date

SEED = 42
ANCHOR_DATE = date(2025, 10, 15)
ACTIVITY_END = ANCHOR_DATE
ACTIVITY_START = date(2025, 10, 9)  # 7 inclusive days

# Per-module row budgets (target ~210K total, within 200-220K range).
# Row counts here are ROWS GENERATED BY BULK SEED, not totals incl. smoke seed.
CARDINALITIES = {
    "operational": {
        "riders": 50,
        "ad_campaigns": 20,
        "ad_placements": 60,
        "promotions": 25,
        "price_lists": 15,
        "price_list_items": 300,
    },
    "users": {
        "users": 3_500,
        "addresses": 4_500,
    },
    "inventory": {
        "store_inventory": 120,         # 10 active products × 12 stores
        "inventory_movements": 25_000,
    },
    "orders": {
        "carts": 13_000,
        "orders": 10_000,
        "order_items": 30_000,
        "order_events": 40_000,
        "payments": 10_000,
        "refunds": 500,
    },
    "engagement": {
        "app_events": 30_000,
        "search_queries": 10_000,
        "push_notifications": 8_000,
        "pipeline_runs": 200,
    },
    "advertising": {
        "ad_impressions": 20_000,
        "ad_clicks": 2_000,
        "ad_attributions": 3_500,
    },
    "orphans": {
        "products": 50,
    },
}

# Smoke seed ID ranges — bulk must NOT collide
SMOKE_MAX_USER_ID = 5
SMOKE_MAX_ADDRESS_ID = 5
SMOKE_MAX_CART_ID = 1
SMOKE_MAX_ORDER_ID = 3
SMOKE_MAX_ORDER_ITEM_ID = 4
SMOKE_MAX_RIDER_ID = 3
SMOKE_MAX_PRODUCT_ID = 10
SMOKE_MAX_PRODUCT_ATTR_ID = 18
SMOKE_MAX_ORDER_EVENT_ID = 5

# Used for #6: pre-2023 date floor for "legacy bad rows" in smoke seed only
LEGACY_DATE_FLOOR = date(2023, 12, 31)

# City split (must match smoke seed cities table)
CITY_DISTRIBUTION = {1: 0.50, 2: 0.35, 3: 0.15}  # BLR, BOM, PNQ
CITY_CODES = {1: "BLR", 2: "BOM", 3: "PNQ"}


def sub_seed(module_name: str) -> int:
    """Derive a stable per-module seed from the global SEED + module name.

    Isolates RNG state so regenerating one module doesn't shift others' output.
    """
    h = hashlib.sha256(module_name.encode("utf-8")).digest()
    return int.from_bytes(h[:8], "big") ^ SEED
